before_install:
- sudo apt-get install cmake libv4l-dev liblog4cpp5-dev
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/liblivemedia-dev_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/libbasicusageenvironment0_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/libgroupsock1_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/liblivemedia23_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/libusageenvironment1_2014.01.13-1_amd64.deb
- sudo dpkg -i liblivemedia-dev_2014.01.13-1_amd64.deb libbasicusageenvironment0_2014.01.13-1_amd64.deb libgroupsock1_2014.01.13-1_amd64.deb liblivemedia23_2014.01.13-1_amd64.deb libusageenvironment1_2014.01.13-1_amd64.deb
- rm *.deb
language: cpp
compiler:
- gcc
script:
- cmake .
- make
- cpack .
env:
  global:
  - secure: hcQTuiLgzgWcinU2QKOlVI7xe0/XWAf6PnBbQG6YI7CkoQWMOaayime+07CpkRFM83GnZ7pc6qeA+RzVjwTZVfyIM8/T0af0mSNqop/ciflFa8t6v3k4nmUsWB9Cw9vEPdfuzsUMU1g7+qGFBMFRQj4lwgxgVll/S9wAUjD14pU=
addons:
  coverity_scan:
    project:
      name: mpromonet/h264_v4l2_rtspserver
    build_command_prepend: cmake .
    build_command: make
    branch_pattern: master
    notification_email: scan_notifications@example.com
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying ${RELEASE_PKG_FILE} to GitHub releases"    
deploy:
  provider: releases
  api_key:
    secure: HvPy3gyZ1nGPLAMgpRvJO2yFqpYBU7HzPQVr8LkBuOIMfya+08fbrQ9lRmvGI/3R4hwx4aPZug2DEfedP07vFXmbISLy/VTeL9TBg86CKX4vPywaoqiv5mTECUp29pmj9R3aCrIK0ROjuXQJqLN1/+jsAEnvh/gBMplQuM6a3Zc=
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    repo: mpromonet/h264_v4l2_rtspserver
    tags: true
